# Generated by Django 6.0.3 on 2026-03-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
