# Generated by Django 6.0.2 on 2026-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(default='Universidad EAFIT', max_length=255),
        ),
    ]
