# Generated by Django 6.0.2 on 2026-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0002_internshipoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='modality',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrido', 'Híbrido')], default='presencial', max_length=10),
        ),
    ]
