# Generated by Django 5.2 on 2026-03-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0002_studentprofile_cv_pdf_alter_companyprofile_id_and_more'),
        ('internshipApp', '0002_studentprofile_is_verified'),
    ]

    operations = [
    ]
