# Generated by Django 6.0.2 on 2026-03-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0003_internshipoffer_modality'),
        ('internshipApp', '0003_merge_20260311_1248'),
    ]

    operations = [
    ]
