# Generated by Django 6.0.2 on 2026-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0003_merge_20260311_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
