# Generated by Django 6.0.2 on 2026-03-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0004_alter_companyprofile_id_alter_studentprofile_id_and_more'),
        ('internshipApp', '0004_merge_20260312_1145'),
    ]

    operations = [
    ]
