# Generated by Django 6.0.2 on 2026-03-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0004_merge_20260312_1145'),
        ('internshipApp', '0006_alter_companyprofile_id_alter_internshipoffer_id_and_more'),
    ]

    operations = [
    ]
