# Generated by Django 6.0.2 on 2026-04-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0004_merge_20260312_1718'),
        ('internshipApp', '0005_internshipapplication'),
        ('internshipApp', '0007_merge_20260313_1619'),
    ]

    operations = [
    ]
