# Generated by Django 6.0.2 on 2026-05-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
