# Generated by Django 6.0.2 on 2026-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_career_remove_studentprofile_career_and_more'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='careers',
            field=models.ManyToManyField(related_name='offers', to='accounts.career'),
        ),
    ]
