# Generated by Django 6.0.2 on 2026-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='career',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='careers',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.career'),
        ),
    ]
